### ISSUE TITLE
update: code Improvements recommended

### ISSUE THREAD

**Issue by ThomasBurleson** [davideast/angular-universal-express#4]
#### [index.ts](https://github.com/davideast/angular-universal-express/blob/master/src/index.ts)

*  `readFile$` use of `Observable.create()` should return a teardown function.
*  instead of `mergmap(...).take(1)`, why not use `switchMap(...)` ?
*  do you need to unsubscribe in `angularUniversal()` to prevent memory locks ?

**Comment by davideast** [comment]
Hey @ThomasBurleson! Thank you for these recommendations.

I overlooked the teardown function, great catch!

As the other two go here are my thoughts:

- I use `mergeMap().take(1)` because it is an Observable way of acting like a promise. The `.take(1)` will close the Observable stream. Using `switchMap()` will keep it open which is unncessary for the situation.
- I don't think an unsubscribe is necessary because of the `.take(1)` which handles the unsubscribe. 

Please let me know if I'm wrong in my understanding and I'll be happy to make the changes.

**Comment by ThomasBurleson** [comment]
@davideast - understood. I like your technique for `mergeMap().take(1)`... thx for your responses.

**Comment by davideast** [comment]
@ThomasBurleson  Thanks for the kind discussion!
